Wrpd enhancement 32
wrappid/wrappid-app pull request #39
Opened 2024-02-01 12:49 UTC by irkfaisal

## Description

Add label/title before packages details. 

## Checklist

- [ ] I have performed a thorough self-review of my code.
- [ ] I have added or updated relevant tests for my changes.
- [ ] My code follows the project's style guidelines and best practices.
- [ ] I have updated the documentation if necessary.
- [ ] I have added or updated relevant comments in my code.
- [ ] I have resolved any merge conflicts of my branch.

## Screenshots (if applicable)

## Additional Notes

## Reviewers

---

## Maintainer Notes

- [ ] Has this change been tested in a staging environment?
- [ ] Does this change introduce any breaking changes or deprecations?

2024-02-01 13:05 UTC, techoneel requested changes
I do not like the architecture of the changes requested.

Please have a discussion with technical team and clear your doubts what was wrong and work on it and fix it.

2024-02-02 03:59 UTC, irkfaisal commented
I have changed the architecture and committed again kindly review.

2024-02-03 15:40 UTC, techoneel requested changes
Remove unnecessary json files

2024-02-03 15:40 UTC, techoneel commented on src/scripts/web-runtime-core-package.json
> +{
Remove unnecessary json files

2024-02-05 19:11 UTC, merged